export const createUserStates = {
  SUCCESS: "SUCCESS",
  USERNAME_NOT_STRING: "USERNAME_NOT_STRING",
  IMGDATA_NOT_STRING: "IMGDATA_NOT_STRING",
  USERNAME_TAKEN: "USERNAME_TAKEN",
  NOT_AUTHORIZED: "NOT_AUTHORIZED"
};

export const checkUserStates = {
  SUCCESS: "SUCCESS",
  SESSION_TOKEN_MISSING: "SESSION_TOKEN_MISSING",
  USER_NOT_IN_SESSION_STORAGE: "USER_NOT_IN_SESSION_STORAGE",
  SESSION_TOKEN_USERNAME_MISMATCH: "SESSION_TOKEN_USERNAME_MISMATCH",
};

export const generalStates = {
  TOO_MUCH_DATA: "TOO_MUCH_DATA",
  COOKIE_ISSUE: "COOKIE_ISSUE",
  NOT_POST: "NOT_POST",
  SERVER_ERROR: "SERVER_ERROR",
};

export const wsServerToClientStates = {
  PING: "PING",
  USER_UPDATED_IMG: "USER_UPDATED_IMG",
  IMG_UPDATED_SUCCESSFULLY: "IMG_UPDATED_SUCCESSFULLY",
  NEW_CONNECTION_SUCCESSFUL: "NEW_CONNECTION_SUCCESSFUL",
  USER_DIED: "USER_DIED",
  OFFER_FROM_SOMEONE: "OFFER_FROM_SOMEONE",
  ANSWER_FROM_SOMEONE: "ANSWER_FROM_SOMEONE",
  PASSING_CANDIDATE: "PASSING_CANDIDATE",
  ERROR: "ERROR"
};

export const wsClientToServerStates = {
  PONG: "PONG",
  NEW_CONNECTION: "NEW_CONNECTION",
  NEW_IMG: "NEW_IMG",
  PASS_OFFER: "PASS_OFFER",
  PASS_ANSWER: "PASS_ANSWER",
  PASS_CANDIDATE: "PASS_CANDIDATE",
  DELETE_USER: "DELETE_USER",
  DO_STUFF: "DO_STUFF"
};